theme = "kanagawa-dragon"

[editor]
line-number = "relative"
mouse = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # binds esc to deselect selected objects instead of ; ,
"C-j" = "move_line_down"  # Try mapping to picker navigation (next item)
"C-k" = "move_line_up"    # Try mapping to picker navigation (previous item)


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
